/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domain.Narudzbina;
import domain.StavkaNarudzbine;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import komunikacija.Komunikacija;
import konstante.Operacije;
import kontroler.KontrolerKI;
import modeli.ModelTabeleStavka;
import transfer.KlijentskiZahtev;

/**
 *
 * @author Nikola
 */
public class IzmenaNarudzbine extends javax.swing.JFrame {
    Narudzbina n;
    NarudzbinaForma nf;

    public Narudzbina getN() {
        return n;
    }

    public void setN(Narudzbina n) {
        this.n = n;
    }

    public NarudzbinaForma getNf() {
        return nf;
    }

    public void setNf(NarudzbinaForma nf) {
        this.nf = nf;
    }
    
    
    
    /**
     * Creates new form IzmenaNarudzbine
     */
    public IzmenaNarudzbine(java.awt.Frame parent, boolean modal) {
        //super(parent, modal);
        initComponents();
        
        srediTabelu();
        
    }
    public IzmenaNarudzbine(java.awt.Frame parent, boolean modal,Narudzbina n) {
        //super(parent, modal);
        initComponents();
        this.n=n;
        srediTabelu();
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
        txtDatum.setText(sdf.format(n.getDatum()));
        this.setTitle("Izmena narudžbine");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSacuvaj = new javax.swing.JButton();
        btnNazad = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStavka = new javax.swing.JTable();
        btnDodaj = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtDatum = new javax.swing.JTextField();
        btnIzmeniStavku = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnSacuvaj.setText("Sacuvaj");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        btnNazad.setText("Nazad");
        btnNazad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNazadActionPerformed(evt);
            }
        });

        tblStavka.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblStavka);

        btnDodaj.setText("Dodaj stavku");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        btnObrisi.setText("Obrisi stavku");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        jLabel1.setText("Datum:");

        btnIzmeniStavku.setText("Izmeni stavku");
        btnIzmeniStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniStavkuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNazad, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(btnDodaj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnIzmeniStavku, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnObrisi)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDodaj)
                    .addComponent(btnObrisi)
                    .addComponent(btnIzmeniStavku))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSacuvaj)
                    .addComponent(btnNazad))
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
        
        ModelTabeleStavka mts = (ModelTabeleStavka) tblStavka.getModel();
        ArrayList<StavkaNarudzbine> listaStavki = mts.getLista();

        if(listaStavki.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Morate uneti bar jednu stavku");
            return;
        }
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
        if(txtDatum.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Datum ne sme biti prazan");
            return;
        }
        try {
            n.setDatum(sdf.parse(txtDatum.getText()));
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Unesite datum u formatu dd.MM.yyyy");
            return;
        }
        n.setLista(listaStavki);
        double ukupnaCena = 0;
        for(StavkaNarudzbine s : listaStavki) {
               ukupnaCena += s.getIznos();
        }
        n.setUkupnaCena(ukupnaCena);
        /*KlijentskiZahtev kz = new KlijentskiZahtev();
        kz.setOperacija(Operacije.izmeni_narudzbinu);
        kz.setParametar(n);
        Komunikacija.getInstance().posaljiZahtev(kz);

        boolean uspesno = (boolean) Komunikacija.getInstance().primiOdgovor().getParametar();*/
        boolean uspesno = KontrolerKI.getInstance().izmeniNarudzbinu(n);
        if(uspesno) {
            JOptionPane.showMessageDialog(this, "Uspesno sacuvana narudzbina");
            nf.srediTabelu();
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Nije uspelo cuvanje narudzbine");
        }
    }//GEN-LAST:event_btnSacuvajActionPerformed

    private void btnNazadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNazadActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnNazadActionPerformed

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
        UnosStavke us = new UnosStavke(this, rootPaneCheckingEnabled);
        us.setVisible(true);
        
        StavkaNarudzbine s = us.getS();
        s.setNarudzbinaid(n.getNarudzbinaid());
        
        ModelTabeleStavka mts = (ModelTabeleStavka) tblStavka.getModel();
        ArrayList<StavkaNarudzbine> lista = mts.getLista();
        int i = 0;
        for(StavkaNarudzbine sn : lista) {
            if(s.getArtikal().getArtikalID() == sn.getArtikal().getArtikalID()) {
               int kolicina = s.getKolicina();
               lista.get(i).setKolicina(lista.get(i).getKolicina()+kolicina);
               tblStavka.setModel(mts);
               mts.osvezi();
               return;
            }
            i++;
        }
        mts.dodaj(s);
        tblStavka.setModel(mts);
    }//GEN-LAST:event_btnDodajActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        ModelTabeleStavka mts = (ModelTabeleStavka) tblStavka.getModel();
        mts.obrisi(tblStavka.getSelectedRow());
        
    }//GEN-LAST:event_btnObrisiActionPerformed

    private void btnIzmeniStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniStavkuActionPerformed
        int i = tblStavka.getSelectedRow();
        if(i==-1) {
            JOptionPane.showMessageDialog(this, "Izaberite stavku za izmenu");
            return;
        }
        ModelTabeleStavka mts = (ModelTabeleStavka) tblStavka.getModel();
        ArrayList<StavkaNarudzbine> lista = mts.getLista();
        StavkaNarudzbine s = lista.get(i);
        UnosStavke us = new UnosStavke(nf, rootPaneCheckingEnabled, s);
        us.setVisible(true);
        
        StavkaNarudzbine novaStavka = us.getS();
        lista.set(i, novaStavka);
        mts.setLista(lista);
        tblStavka.setModel(mts);
    }//GEN-LAST:event_btnIzmeniStavkuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IzmenaNarudzbine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IzmenaNarudzbine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IzmenaNarudzbine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IzmenaNarudzbine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                IzmenaNarudzbine dialog = new IzmenaNarudzbine(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnIzmeniStavku;
    private javax.swing.JButton btnNazad;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblStavka;
    private javax.swing.JTextField txtDatum;
    // End of variables declaration//GEN-END:variables

   
    
    

    private void srediTabelu() {
        ModelTabeleStavka mts = new ModelTabeleStavka();
        mts.setLista(n.getLista());
        tblStavka.setModel(mts);
    }
}
