/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domain.Kupac;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import komunikacija.Komunikacija;
import konstante.Operacije;
import kontroler.KontrolerKI;
import modeli.ModelTabeleKupac;
import transfer.KlijentskiZahtev;

/**
 *
 * @author Nikola
 */
public class KupciForma extends javax.swing.JFrame {

    /**
     * Creates new form KupciForma
     */
    public KupciForma() {
        initComponents();
        srediTabelu();
        this.setTitle("Forma za pretragu kupaca");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtIme = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKupci = new javax.swing.JTable();
        btnPretrazi = new javax.swing.JButton();
        btnDodaj = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();
        btnIzmeni = new javax.swing.JButton();
        btnNazad = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtPrezime = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ime: ");

        tblKupci.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblKupci);

        btnPretrazi.setText("Pretrazi");
        btnPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziActionPerformed(evt);
            }
        });

        btnDodaj.setText("Dodaj kupca");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        btnObrisi.setText("Obrisi kupca");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        btnIzmeni.setText("Izmeni");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        btnNazad.setText("Nazad");
        btnNazad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNazadActionPerformed(evt);
            }
        });

        jLabel2.setText("Prezime:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDodaj)
                        .addGap(28, 28, 28)
                        .addComponent(btnIzmeni)
                        .addGap(41, 41, 41)
                        .addComponent(btnObrisi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNazad))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(40, 40, 40)
                                .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtPrezime)))
                        .addGap(39, 39, 39)
                        .addComponent(btnPretrazi)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPretrazi))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDodaj)
                    .addComponent(btnObrisi)
                    .addComponent(btnIzmeni)
                    .addComponent(btnNazad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziActionPerformed
        String ime = "";
        String prezime = "";
        
        if(txtIme.getText().isEmpty() || txtPrezime.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Unesite ime i prezime");
            return;
        }
        ime = txtIme.getText();
        prezime = txtPrezime.getText();
        
        /*KlijentskiZahtev kz = new KlijentskiZahtev();
        kz.setOperacija(Operacije.vrati_kupce);
        String[] parametri = {ime,prezime};
        kz.setParametar(parametri);
        Komunikacija.getInstance().posaljiZahtev(kz);
        
        ArrayList<Kupac> lista = (ArrayList<Kupac>) Komunikacija.getInstance().primiOdgovor().getParametar();*/
        String[] parametri = {ime,prezime};
        ArrayList<Kupac> lista = KontrolerKI.getInstance().vratiKupce(parametri);
        if(lista.size() > 0) {
            JOptionPane.showMessageDialog(this, "Pretraga je uspešno završena");
        } else {
            JOptionPane.showMessageDialog(this, "Sistem nije pronašao kupce koji odgovaraju zadatim kriterijumima");
            return;
        }
        ModelTabeleKupac mtk = (ModelTabeleKupac) tblKupci.getModel();
        mtk.setLista(lista);
        tblKupci.setModel(mtk);
    }//GEN-LAST:event_btnPretraziActionPerformed

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
       UnosKupca uk = new UnosKupca(this, rootPaneCheckingEnabled);
       uk.setVisible(true);
       
       Kupac k = uk.getK();
       if(k.getIme().equals("")) {
           return;
       }
       ModelTabeleKupac mtk = (ModelTabeleKupac) tblKupci.getModel();
       mtk.dodaj(k);
       tblKupci.setModel(mtk);
    }//GEN-LAST:event_btnDodajActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
        ModelTabeleKupac mtk = (ModelTabeleKupac) tblKupci.getModel();
        int red = tblKupci.getSelectedRow();
        if(red == -1) {
            JOptionPane.showMessageDialog(this, "Izaberite narudžbinu");
            return;
        }
        Kupac k = mtk.getLista().get(red);
        UnosKupca uk = new UnosKupca(this, rootPaneCheckingEnabled, k);
        uk.setVisible(true);
        
        Kupac kupac = uk.getK();
        mtk.obrisi(red);
        mtk.dodaj(kupac);
        tblKupci.setModel(mtk);
    }//GEN-LAST:event_btnIzmeniActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        ModelTabeleKupac mtk = (ModelTabeleKupac) tblKupci.getModel();
        int red = tblKupci.getSelectedRow();
        int kupacid = mtk.getLista().get(red).getKupacid();
        
        /*KlijentskiZahtev kz = new KlijentskiZahtev();
        kz.setOperacija(Operacije.obrisi_kupca);
        kz.setParametar(kupacid);
        Komunikacija.getInstance().posaljiZahtev(kz);
        
        boolean uspesno = (boolean) Komunikacija.getInstance().primiOdgovor().getParametar();*/
        boolean uspesno = KontrolerKI.getInstance().obrisiKupca(kupacid);
        if(uspesno) {
            JOptionPane.showMessageDialog(this, "Uspesno obrisan kupac");
            srediTabelu();
        } else {
            JOptionPane.showMessageDialog(this, "Neuspesno obrisan kupac");
        }
    }//GEN-LAST:event_btnObrisiActionPerformed

    private void btnNazadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNazadActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnNazadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KupciForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KupciForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KupciForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KupciForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KupciForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnNazad;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnPretrazi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblKupci;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtPrezime;
    // End of variables declaration//GEN-END:variables

    private void srediTabelu() {
        ModelTabeleKupac mtk = new ModelTabeleKupac();
        //KlijentskiZahtev kz = new KlijentskiZahtev();
        String[] parametri = {"",""};
        //kz.setParametar(parametri);
        //kz.setOperacija(Operacije.vrati_kupce);
        //Komunikacija.getInstance().posaljiZahtev(kz);
        
        //ArrayList<Kupac> lista = (ArrayList<Kupac>) Komunikacija.getInstance().primiOdgovor().getParametar();
        ArrayList<Kupac> lista = KontrolerKI.getInstance().vratiKupce(parametri);
        mtk.setLista(lista);
        tblKupci.setModel(mtk);
        
    }
}
