/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domain.Kupac;
import domain.Narudzbina;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import komunikacija.Komunikacija;
import konstante.Operacije;
import kontroler.KontrolerKI;
import modeli.ModelTabeleNarudzbina;
import pomocna.PretragaNarudzbina;
import transfer.KlijentskiZahtev;

/**
 *
 * @author Nikola
 */
public class NarudzbinaForma extends javax.swing.JFrame {

    /**
     * Creates new form KlijentskaForma
     */
    public NarudzbinaForma() {
        initComponents();
        srediCMB();
        srediTabelu();
        this.setTitle("Pregled narudžbina");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblNarudzbina = new javax.swing.JTable();
        txtDatum = new javax.swing.JTextField();
        btnPretraga = new javax.swing.JButton();
        chbDatum = new javax.swing.JCheckBox();
        cmbKupac = new javax.swing.JComboBox();
        chbKupac = new javax.swing.JCheckBox();
        btnUnesi = new javax.swing.JButton();
        btnIzmeni = new javax.swing.JButton();
        btnIzbrisi = new javax.swing.JButton();
        btnNazad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblNarudzbina.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblNarudzbina);

        btnPretraga.setText("Pretrazi");
        btnPretraga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretragaActionPerformed(evt);
            }
        });

        chbDatum.setText("Pretraga po datumu");

        cmbKupac.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        chbKupac.setText("Pretraga po kupcu");

        btnUnesi.setText("Unesi novu narudzbinu");
        btnUnesi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnesiActionPerformed(evt);
            }
        });

        btnIzmeni.setText("Izmeni");
        btnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzmeniActionPerformed(evt);
            }
        });

        btnIzbrisi.setText("Obrisi ");
        btnIzbrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzbrisiActionPerformed(evt);
            }
        });

        btnNazad.setText("Nazad");
        btnNazad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNazadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chbDatum)
                                    .addComponent(chbKupac)
                                    .addComponent(btnPretraga))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbKupac, 0, 130, Short.MAX_VALUE)
                                    .addComponent(txtDatum)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnUnesi)
                                .addGap(36, 36, 36)
                                .addComponent(btnIzmeni)
                                .addGap(38, 38, 38)
                                .addComponent(btnIzbrisi)
                                .addGap(38, 38, 38)
                                .addComponent(btnNazad)))
                        .addGap(0, 312, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chbDatum)
                    .addComponent(txtDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbKupac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chbKupac))
                .addGap(18, 18, 18)
                .addComponent(btnPretraga)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUnesi)
                    .addComponent(btnIzmeni)
                    .addComponent(btnIzbrisi)
                    .addComponent(btnNazad))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPretragaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretragaActionPerformed
        String datum = "";
        String kupacid = "";
        
        if(chbDatum.isSelected()) {
            SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
            SimpleDateFormat sdf2 = new SimpleDateFormat("yyyy-MM-dd");
            datum = txtDatum.getText();
            if(datum.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Unesite datum");
                return;
            }
            try {
                Date testDatum = sdf.parse(datum);
                datum = sdf2.format(testDatum);
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(this, "Unesite datum u formatu dd.MM.yyyy ");
                return;
            }
            
        }
        
        if(chbKupac.isSelected()) {
            Kupac kupac = (Kupac) cmbKupac.getSelectedItem();
            kupacid = Integer.toString(kupac.getKupacid());
        }
        
        String[] parametri = {datum,kupacid};
        /*KlijentskiZahtev kz = new KlijentskiZahtev();
        kz.setOperacija(Operacije.vrati_pretragu_narudzbina);
        kz.setParametar(parametri);
        Komunikacija.getInstance().posaljiZahtev(kz);
        
        ArrayList<PretragaNarudzbina> lista = (ArrayList<PretragaNarudzbina>) Komunikacija.getInstance().primiOdgovor().getParametar();*/
        ArrayList<PretragaNarudzbina> lista = KontrolerKI.getInstance().vratiNarudzbine(parametri);
        if(lista.size() > 0) {
            JOptionPane.showMessageDialog(this, "Pretraga je uspešno završena");
        } else {
            JOptionPane.showMessageDialog(this, "Sistem nije pronašao narudžbine koje odgovaraju zadatim kriterijumima");
            return;
        }
        ModelTabeleNarudzbina mtn = (ModelTabeleNarudzbina) tblNarudzbina.getModel();
        mtn.setLista(lista);
        tblNarudzbina.setModel(mtn);
    }//GEN-LAST:event_btnPretragaActionPerformed

    private void btnNazadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNazadActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnNazadActionPerformed

    private void btnUnesiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnesiActionPerformed
        UnosNarudzbine un = new UnosNarudzbine(this, rootPaneCheckingEnabled);
        un.setLocationRelativeTo(this);
        un.setVisible(true);
        
        srediTabelu();
    }//GEN-LAST:event_btnUnesiActionPerformed

    private void btnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzmeniActionPerformed
       ModelTabeleNarudzbina mtn = (ModelTabeleNarudzbina) tblNarudzbina.getModel();
       ArrayList<PretragaNarudzbina> lista = mtn.getLista();
       int i = tblNarudzbina.getSelectedRow();
        if(i == -1) {
            JOptionPane.showMessageDialog(this, "Izaberite narudžbinu");
            return;
        }
       int narudzbinaID = lista.get(i).getNarudzbinaid();
        
       String narID = Integer.toString(narudzbinaID);
       String[] parametri = {"",narID};
       /*KlijentskiZahtev kz = new KlijentskiZahtev();
       kz.setOperacija(Operacije.vrati_jednu_narudzbinu);
       kz.setParametar(parametri);
       Komunikacija.getInstance().posaljiZahtev(kz);
       
       Narudzbina n = (Narudzbina) Komunikacija.getInstance().primiOdgovor().getParametar();*/
       Narudzbina n = KontrolerKI.getInstance().vratiJednuNarudzbinu(parametri);
       IzmenaNarudzbine in = new IzmenaNarudzbine(this, rootPaneCheckingEnabled,n);
       in.setNf(this);
       in.setLocationRelativeTo(this);
       in.setVisible(true);
    }//GEN-LAST:event_btnIzmeniActionPerformed

    private void btnIzbrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzbrisiActionPerformed
       ModelTabeleNarudzbina mtn = (ModelTabeleNarudzbina) tblNarudzbina.getModel();
       ArrayList<PretragaNarudzbina> lista = mtn.getLista();
       int i = tblNarudzbina.getSelectedRow();
       if(i == -1) {
            JOptionPane.showMessageDialog(this, "Izaberite narudžbinu");
            return;
        }
       int narudzbinaID = lista.get(i).getNarudzbinaid();
       
       /*KlijentskiZahtev kz = new KlijentskiZahtev();
       kz.setOperacija(Operacije.obrisi_narudzbinu);
       kz.setParametar(narudzbinaID);
       Komunikacija.getInstance().posaljiZahtev(kz);
       boolean uspesno = (boolean) Komunikacija.getInstance().primiOdgovor().getParametar();*/
       boolean uspesno = KontrolerKI.getInstance().obrisiNarudzbinu(narudzbinaID);
       if(uspesno) {
           JOptionPane.showMessageDialog(this, "Uspesno izbrisana narudzbina");
           srediTabelu();
       } else {
           JOptionPane.showMessageDialog(this, "Greska prilikom brisanja narudzbine");
       }
    }//GEN-LAST:event_btnIzbrisiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NarudzbinaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NarudzbinaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NarudzbinaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NarudzbinaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NarudzbinaForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzbrisi;
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnNazad;
    private javax.swing.JButton btnPretraga;
    private javax.swing.JButton btnUnesi;
    private javax.swing.JCheckBox chbDatum;
    private javax.swing.JCheckBox chbKupac;
    private javax.swing.JComboBox cmbKupac;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblNarudzbina;
    private javax.swing.JTextField txtDatum;
    // End of variables declaration//GEN-END:variables

    private void srediCMB() {
        /*KlijentskiZahtev kz = new KlijentskiZahtev();
        kz.setOperacija(Operacije.vrati_kupce);
        String[] parametri = {"",""};
        kz.setParametar(parametri);
        Komunikacija.getInstance().posaljiZahtev(kz);
        
        ArrayList<Kupac> lista = (ArrayList<Kupac>) Komunikacija.getInstance().primiOdgovor().getParametar();*/
        String[] parametri = {"",""};
        ArrayList<Kupac> lista = KontrolerKI.getInstance().vratiKupce(parametri);
        cmbKupac.removeAllItems();
        
        for(Kupac k : lista) {
            cmbKupac.addItem(k);
        }
    }

    public void srediTabelu() {
        ModelTabeleNarudzbina mtn = new ModelTabeleNarudzbina();
        /*KlijentskiZahtev kz = new KlijentskiZahtev();
        String[] parametri = {"",""};
        kz.setOperacija(Operacije.vrati_pretragu_narudzbina);
        kz.setParametar(parametri);
        Komunikacija.getInstance().posaljiZahtev(kz);
        
        ArrayList<PretragaNarudzbina> lista = (ArrayList<PretragaNarudzbina>) Komunikacija.getInstance().primiOdgovor().getParametar();*/
        String[] parametri = {"",""};
        ArrayList<PretragaNarudzbina> lista = KontrolerKI.getInstance().vratiNarudzbine(parametri);
        mtn.setLista(lista);
        tblNarudzbina.setModel(mtn);
    }
}
